# CentralGauge Configuration
# Configuration for Business Central AL code generation benchmark

# Default models for different scenarios
defaultModels:
  benchmark: [sonnet, gpt-4o] # Models for production benchmarks
  development: [mock] # Models for development/testing
  comparison: [claude-4.5, gpt-5] # Flagship models for comparison

# LLM provider settings
llm:
  temperature: 0.1 # Lower = more deterministic
  maxTokens: 4000 # Maximum response length
  timeout: 60000 # Request timeout in milliseconds (60s for complex tasks)

# Benchmark execution settings
benchmark:
  attempts: 2 # Number of attempts per task
  outputDir: results # Directory for benchmark results
  templateDir: templates # Directory for prompt templates

# Container settings - configured for Cronus27
container:
  provider: bccontainer # Use real BC container (bccontainer, docker, mock)
  name: Cronus27 # Container name
  bcVersion: "27.0" # Business Central version
  memoryLimit: 8G # Container memory limit
  credentials:
    username: sshadows # Container authentication username
    password: "1234" # Container authentication password

# Environment variable overrides (optional)
# These will be set during execution
# environment:
#   ANTHROPIC_API_KEY: sk-ant-...
#   OPENAI_API_KEY: sk-...

# Named system prompts for model variants
# Reference these in variant specs: sonnet@prompt=strict-al
# systemPrompts:
#   strict-al:
#     content: |
#       You are a strict AL code generator for Business Central.
#       Only output valid AL code without explanations.

# Named variant profiles for comparing same model with different configs
# Reference these in model specs: sonnet@profile=conservative
variantProfiles:
  conservative:
    description: "Low temperature for deterministic output"
    config:
      temperature: 0.1
      maxTokens: 4000
  creative:
    description: "Higher temperature for varied solutions"
    config:
      temperature: 0.8
      maxTokens: 8000
      systemPromptName: strict-al
  deep-thinking:
    description: "Extended reasoning for complex tasks"
    config:
      temperature: 0.2
      thinkingBudget: 50000
