# Default AL Agent Configuration
#
# This is the baseline agent for AL code generation benchmarks.
# Uses Claude Code's system prompt with appended workflow instructions.

id: default
name: "Default AL Agent"
description: "Baseline autonomous AL code generator with compile/test feedback"
model: claude-sonnet-4-5-20250929
maxTurns: 20
maxTokens: 100000

# Claude Code feature loading
# - project: Loads CLAUDE.md and skills from workingDir
settingSources:
  - project

# SDK built-in tools the agent can use
allowedTools:
  - Read # Read AL files
  - Write # Create new AL files
  - Edit # Modify existing AL files
  - Glob # Find files by pattern
  - Grep # Search file contents
  - Bash # Run shell commands
  - Skill # Use skills from .claude/skills/

# MCP servers for AL compilation and testing
# Note: The path is relative to cwd (CentralGauge root)
mcpServers:
  al-tools:
    command: deno
    args:
      - run
      - --allow-all
      - U:/Git/CentralGuage/mcp/al-tools-server.ts

# Use Claude Code's system prompt with appended workflow instructions
systemPrompt:
  preset: claude_code
  append: |
    ## AL Code Generation Workflow

    You are generating AL code for Microsoft Dynamics 365 Business Central.
    Follow this workflow:

    1. Read the task description carefully
    2. Write the required AL code to .al files in the workspace
    3. Create an app.json manifest if not present
    4. Use the mcp__al-tools__al_compile tool to compile your code
    5. If compilation fails, read the errors, fix the code, and recompile
    6. Repeat until compilation succeeds
    7. If tests are required, use mcp__al-tools__al_test after compilation

    IMPORTANT:
    - Use mcp__al-tools__al_compile (NOT bash "al compile") to compile
    - The projectDir parameter must be the absolute path to your workspace
    - Fix all compilation errors before proceeding
    - Follow AL naming conventions (PascalCase, etc.)

limits:
  maxCompileAttempts: 15
  timeoutMs: 300000

tags:
  - baseline
  - al-generation
